---
- name: Install required packages
  action: apt 
    pkg={{item}} 
    state=installed
  with_items:
    - git
    - gcc
    - make
    - autoconf
    - automake
    - python-dev 
    - libmysqlclient-dev 
    - python-pip
  become: true

- name: Cleanup before we start
  file:
    path={{ project_path }}
    state=absent
  become: true

- name: Setup the Git repo
  git: 
    repo=https://github.com/nalle/dyndd.git 
    dest={{ project_path }} 
    accept_hostkey=yes

- name: Install package
  shell: "python setup.py install" 
  args: 
    chdir: "{{ project_path }}"
  become: true

- name: Check if we need to install config 
  stat: path=/etc/dyndd/dyndd.conf
  register: install_config

- name: Create configuration directory
  file: 
    path=/etc/dyndd
    state=directory 
    mode=0755
  when: install_config.stat.exists == False

- name: Copy configuration file
  shell: "cp /tmp/dyndd/config/dyndd.conf /etc/dyndd/dyndd.conf"
  when: install_config.stat.exists == False
  become: true

- name: Copy bin file
  shell: "cp /tmp/dyndd/bin/dyndd /usr/bin/dyndd"
  become: true

- name: Copy logrotate file
  shell: "cp /tmp/dyndd/logrotate.d/dyndd /etc/logrotate.d/dyndd"
  become: true

- name: Copy startup script
  shell: "cp /tmp/dyndd/startupscripts/dyndd /etc/init.d/dyndd"
  become: true

- name: (Re)start dyndd service 
  service: 
    name=dyndd
    state=restarted 
    enabled=yes 
  become: true

